#
# Author: Christian Alexander <alexforsale@yahoo.com>
#
variables: secrets.yml

templates:

  global:
# semua task akan berhenti jika sisa space untuk path - path dibawah ini kurang
# dari 5000mb
    free_space:
      path: '{? media.partition ?}'
      space: 5000
    pathscrub: windows
    no_entries_ok: yes

tasks:
  versioncheck:
    version_checker:
      check_for_dev_version: yes
      interval: 1

