#
# Author: Christian Alexander <alexforsale@yahoo.com>
#
secrets: secrets.yml

templates:

# setting global untuk transmission-daemon
# perlu disesuaikan dengan konfigurasi transmission di /etc/transmission-daemon/settings.json
  transmission-global:
    transmission:
      enabled: yes
      host: localhost
      port: 9091
      username: transmission
      password: transmission
      ratio: 1 # orang baik seed dengan ratio >4 saya bukan orang baik - baik
      include_subs: yes
    retry_failed:
      retry_time: 10 seconds
      retry_time_multiplier: 1
      max_retries: 4

# berfungsi untuk generate rss
  rssout:
    make_rss:
      encoding: utf-8
      file: '/home/{{ secrets.user }}/downloads.rss'
      days: 1

# list rss
  rss-tv:
    inputs:
      - rss: { url: 'https://eztv.ag/ezrss.xml' }
      - rss: { url: 'http://www.torlock.com/television/rss.xml' }
      - rss: { url: 'https://rarbg.to/rssdd.php?category=tv' }
      - rss: { url: 'http://extratorrent.cc/rss.xml?cid=8&type=last' }
      - rss: { url: 'https://www.limetorrents.cc/rss/20/' }
# filter pertama untuk file yang akan didownload berdasarkan dari size
# pastikan juga filter ini masuk range dari quality yang dicantumkan
# untuk tv show dengan filter quality "!720p+"
    content_size:
      max: 900
      min: 20

# 2 rss dari shanaproject ini hanya contoh, belum terisi oleh daftar anime
  rss-anime:
    inputs:
      - rss: { url: 'http://www.nyaa.eu/?page=rss&cats=1_37&term=horriblesubs&filter=2' }
      - rss: { url: 'http://extratorrent.cc/rss.xml?cid=1&type=last' }
      - rss: { url: 'https://www.limetorrents.cc/rss/1/' }
      - rss: { url: 'http://www.shanaproject.com/feeds/user/38788/' }
      - rss: { url: 'http://www.shanaproject.com/feeds/secure/user/38788/7ZTAXAUBMJ/' }
# untuk anime 300mb+ sudah keterlaluan
    content_size:
      max: 400
      min: 20

  rss-movies:
    inputs:
      - rss: { url: 'https://kat.am/movies/?rss=1' }
      - rss: { url: 'https://yts.ag/rss' }
      - rss: { url: 'https://rarbg.to/rssdd.php?category=movies' }
      - rss: { url: 'http://extratorrent.cc/rss.xml?cid=4&type=last' }
      - rss: { url: 'https://www.limetorrents.cc/rss/16/' }
    content_size:
      max: 4000
      min: 20    

# template untuk TV series
  tv:
    set:
      label: tv
    transmission:
      path: /home/alexforsale/torrent/Series/{{tvdb_series_name}}
# scrape folder tujuan agar tidak terjadi download double
    exists_series:
      - /mnt/TOSHIBA/Movies/Series
# penambahan tv series baru bisa dari banyak sumber
    configure_series:
# untuk thetvdb.com perlu registrasi dan mengisi list tv series disana
      from:
        thetvdb_list:
          username: '{{ secrets.thetvdb.user }}'
          account_id: '{{ secrets.thetvdb.id }}'

# namun bisa juga dengan membaca folder tujuan, cukup membuat folder baru
# di exists_series dengan catatan nama folder harus sesuai dengan yang 
# tercantum di database thetvdb, karena lookupnya disite tersebut.
# disini sengaja dicomment
#    configure_series:
#      from:
#        filesystem:
#          - /mnt/TOSHIBA/Movies/Series
    thetvdb_lookup: yes
    series:
      settings:
        tv:
# untuk list quality bisa dilihat di http://flexget.com/Plugins/quality
          quality: "!720p+"
# pushbullet yang nantinya akan mengirim notifikasi jika ada file yang didownload
# bisa ditentukan jika ingin hanya kirim ke device tertentu dengan tambahan 'device:'
# berguna untuk mengirim notifikasi ke android, atau ke chrome/chromium
    pushbullet:
      apikey: "{{ secrets.pushbullet.apikey }}"
      title: "{{ series_name }} {{ series_id }}"
      body: "{{ title }}\n\nSize: {{ content_size }}MB"

# template untuk movies
  movies:
    set:
      label: movies
    transmission:
      path: /home/alexforsale/torrent/Movies
    exists_movie:
      path: /mnt/TOSHIBA/Movies/Movies
      lookup: imdb
# boleh double asal quality better
      allow_different_qualities: better
    imdb_lookup: yes
    quality: webrip+
    torrent_alive: 10
    list_match:
      from:
        - movie_list: mymovies
# filter berdasarkan filename
    regexp:
      from: title
      reject:
        - msd
        - afg
        - line
        - hc
        - korsub
    pushbullet:
      apikey: "{{ secrets.pushbullet.apikey }}"
      title: "{{ imdb_name }}"
      body: "{{ title }}\n \nSize: {{ content_size }}MB"

# template untuk movies
  anime:
    set:
      label: anime
    transmission:
      path: /home/alexforsale/torrent/anime/{{series_name}}
    exists_series:
      - /mnt/TOSHIBA/Movies/anime/{{series_name}}
# sama dengan tv series, penambahan anime baru cukup dengan membuat
# folder baru sesuai dengan nama anime yang akan didownload.
    configure_series:
      from:
        filesystem:
          - /mnt/TOSHIBA/Movies/anime
    thetvdb_lookup: yes
    pushbullet:
      apikey: "{{ secrets.pushbullet.apikey }}"
      title: "{{ series_name }} {{ series_id }}"
      body: "{{ title }}\n\nSize: {{ content_size }}MB"

# disini semua template diatas digunakan
tasks:

  tv-download:
    priority: 1
    template: [transmission-global, tv, rss-tv, rssout]

  movies-download:
    priority: 2
    template: [transmission-global, movies, rss-movies, rssout]

  anime-download:
    priority: 3
    template: [transmission-global, anime, rss-anime, rssout]

# task ini berguna untuk memasukkan daftar film dari list watchlist di
# trakt.tv kedalam list flexget (mymovies), yang akan dijadikan acuan 
# untuk download dari rss
  import-movie-list:
    trakt_list:
      username: '{{ secrets.trakt.user }}'
      account: '{{ secrets.trakt.account }}'
      list: watchlist
      type: movies
    accept_all: yes
    seen: local
    list_add:
      - movie_list: mymovies

# piratebay
  movies-search:
    trakt_lookup: yes
    priority: 10 # jika kurang dari 10 seeder tidak akan dipakai
    discover:
      what:
        - movie_list: mymovies
      from:
        - piratebay: yes
      interval: 6 hours # bisa menggunakan minutes, hours, atau days
    torrent_alive: 10
    quality: dvdrip+
    template: [transmission-global, rssout]
    transmission:
      path: /mnt/TOSHIBA/Movies/Movies
    set:
      label: movies
    pushbullet:
      apikey: "{{ secrets.pushbullet.apikey }}"
      title: "{{ imdb_name }}"
      body: "{{ title }}\n \nSize: {{ content_size }}MB"

# kirim email yang berisi download.rss ke email yang ditentukan
# dengan interval 1 hari
  emailfeed:
    rss:
      url: '/home/{{ secrets.user }}/downloads.rss'
    disable: [ seen ]
    metainfo_series: yes
    thetvdb_lookup: yes
    imdb_lookup: yes
    tmdb_lookup: yes
    accept_all: yes
    email:
      from: '\{{ secrets.email.from }}'
      to: '\{{ secrets.email.to }}'
      subject: 'Flexget'
      template: html
      smtp_host: smtp.gmail.com
      smtp_port: 587
      smtp_username: '\{{ secrets.email.smtp-user }}'
      smtp_password: '\{{ secrets.email.smtp-pass }}'
      smtp_tls: yes
    interval: 1 days

# pindahkan file dari folder download ke exists
  move-series:
    priority: 31
    disable:
      - seen
      - seen_info_hash
      - retry_failed
    metainfo_series: yes
    thetvdb_lookup: yes
    filesystem:
      path: /home/alexforsale/torrent/Series/
      recursive: yes
      retrieve: files
      regexp: '.*\.(avi|mkv|mp4)$'
    accept_all: yes
    move:
      to: '/mnt/TOSHIBA/Movies/Series/{{tvdb_series_name}}'
      along:
        extensions:
          - srt
          - sub
        subdirs:
          - subs
    exec:
      on_exit:
        phase: find /home/alexforsale/torrent/Series/* -type d -empty -delete

# pindahkan file dari folder download ke exists
  move-movies:
    priority: 32
    disable:
      - seen
      - seen_info_hash
      - retry_failed
    metainfo_series: yes
    thetvdb_lookup: yes
    filesystem:
      path: /home/alexforsale/torrent/Movies/
      recursive: yes
      retrieve: files
      regexp: '.*\.(avi|mkv|mp4)$'
    move:
      to: '/mnt/TOSHIBA/Movies/Movies'
      along:
        extensions:
          - srt
          - sub
        subdirs:
          - subs
    exec:
      on_exit:
        phase: find /home/alexforsale/torrent/Movies/* -type d -empty -delete

# pindahkan file dari folder download ke exists
  move-anime:
    priority: 33
    disable:
      - seen
      - seen_info_hash
      - retry_failed
    parsing:
      series: guessit
    filesystem:
      path: /home/alexforsale/torrent/anime/
      recursive: yes
      retrieve: files
      regexp: '.*\.(avi|mkv|mp4)$'
    metainfo_series: yes
    move:
      to: '/mnt/TOSHIBA/Movies/anime/{{series_name}}'
    exec:
      allow_background: yes
      on_exit:
        phase: find /home/alexforsale/torrent/anime/* -type d -empty -delete


# hapus list transmission yang sudah selesai didownload lebih dari 1 jam
  clean-up:
    clean_transmission:
      host: localhost
      port: 9091
      username: transmission
      password: transmission
      finished_for: 1 hours
    disable: details

# bisa juga dicantumkan dalam task, seperti di task movies-search
schedules:

  - tasks: [move-series, move-movies, move-anime, clean-up]
    interval:
      hours: 1

  - tasks: [tv-download, anime-download]
    interval:
      hours: 2

  - tasks: [import-movie-list, movies-download]
    interval:
      hours: 4
