#
# Author: Christian Alexander <alexforsale@yahoo.com>
#
secrets: secrets.yml


templates:

# reject secara global
  reject:
    regexp:
      reject:
        - (s|d)ub(s|bed|lado|titulado)?\b
        - \bdual\b
        - \b3d\b
        - \b(fr)(ench)?\b
        - \b(ita)(lian)?\b
        - \b(spa)(nish)?\b
        - \b(ger)(man)?\b
        - \bcastellano\b
        - \brus(sian)?\b
        - \bportugese?\b
    content_filter:
      reject:
        - '*.rar'
        - '*.zip'


# setting global untuk transmission-daemon
# perlu disesuaikan dengan konfigurasi transmission di /etc/transmission-daemon/settings.json
  transmission-global:
    transmission:
      enabled: yes
      host: localhost
      port: 9091
      username: transmission
      password: transmission
      ratio: 1 # orang baik seed dengan ratio >4 saya bukan orang baik - baik
      include_subs: yes
    retry_failed:
      retry_time: 10 seconds
      retry_time_multiplier: 1
      max_retries: 4

# list rss
  rss-tv:
    inputs:
      - rss: { url: 'https://eztv.ag/ezrss.xml' }
      - rss: { url: 'http://www.torlock.com/television/rss.xml' }
      - rss: { url: 'https://rarbg.to/rssdd.php?category=tv' }
      - rss: { url: 'http://extratorrent.cc/rss.xml?cid=8&type=last' }
      - rss: { url: 'https://www.limetorrents.cc/rss/20/' }

# 2 rss dari shanaproject ini hanya contoh, belum terisi oleh daftar anime
  rss-anime:
    inputs:
      - rss: { url: 'http://www.nyaa.eu/?page=rss&cats=1_37&term=horriblesubs&filter=2' }
      - rss: { url: 'http://extratorrent.cc/rss.xml?cid=1&type=last' }
      - rss: { url: 'https://www.limetorrents.cc/rss/1/' }
      - rss: { url: 'http://www.shanaproject.com/feeds/user/38788/' }
      - rss: { url: 'http://www.shanaproject.com/feeds/secure/user/38788/7ZTAXAUBMJ/' }

  rss-movies:
    inputs:
      - rss: { url: 'https://kat.am/movies/?rss=1' }
      - rss: { url: 'https://yts.ag/rss' }
      - rss: { url: 'https://rarbg.to/rssdd.php?category=movies' }
      - rss: { url: 'http://extratorrent.cc/rss.xml?cid=4&type=last' }
      - rss: { url: 'https://www.limetorrents.cc/rss/16/' }

# template untuk TV series
  tv:
    set:
      label: tv
    transmission:
      path: '/home/{{ secrets.user }}/torrent/Series/{{tvdb_series_name}}'
# scrape folder tujuan agar tidak terjadi download double
    exists_series: 
      path: '{{ secrets.folder.series }}'
# penambahan tv series baru bisa dari banyak sumber
    configure_series:
# untuk thetvdb.com perlu registrasi dan mengisi list tv series disana
      from:
        thetvdb_list:
          username: '{{ secrets.thetvdb.user }}'
          account_id: '{{ secrets.thetvdb.id }}'

# namun bisa juga dengan membaca folder tujuan, cukup membuat folder baru
# di exists_series dengan catatan nama folder harus sesuai dengan yang 
# tercantum di database thetvdb, karena lookupnya disite tersebut.
# disini sengaja dicomment
#    configure_series:
#      from:
#        filesystem:
#          - /mnt/TOSHIBA/Movies/Series
    thetvdb_lookup: yes
    series:
      settings:
        tv:
# untuk list quality bisa dilihat di http://flexget.com/Plugins/quality
          quality: "!720p+"
          identified_by: ep
# pushbullet yang nantinya akan mengirim notifikasi jika ada file yang didownload
# bisa ditentukan jika ingin hanya kirim ke device tertentu dengan tambahan 'device:'
# berguna untuk mengirim notifikasi ke android, atau ke chrome/chromium
    pushbullet:
      apikey: "{{ secrets.pushbullet.apikey }}"
      title: "{{ series_name }} {{ series_id }}"
      body: "{{ title }}\n\nSize: {{ content_size }}MB"

# template untuk movies
  movies:
    set:
      label: movies
    transmission:
      path: '/home/{{ secrets.user }}/torrent/Movies'
    exists_movie:
      path: '{{ secrets.folder.movies }}'
      lookup: imdb
# boleh double asal quality better
      allow_different_qualities: better
    imdb_lookup: yes
    quality: webrip+
    torrent_alive: 10
    list_match:
      from:
        - movie_list: mymovies
# filter berdasarkan filename
    regexp:
      from: title
      reject:
        - msd
        - afg
        - line
        - hc
        - korsub
    pushbullet:
      apikey: "{{ secrets.pushbullet.apikey }}"
      title: "{{ imdb_name }}"
      body: "{{ title }}\n \nSize: {{ content_size }}MB"

# template untuk movies
  anime:
    set:
      label: anime
    transmission:
      path: '/home/{{ secrets.user }}/torrent/anime/{{series_name}}'
    exists_series: '{{ secrets.folder.anime }}'
# sama dengan tv series, penambahan anime baru cukup dengan membuat
# folder baru sesuai dengan nama anime yang akan didownload.
    configure_series:
      from:
        filesystem:
          - '{{ secrets.folder.anime }}'
    thetvdb_lookup: yes
    pushbullet:
      apikey: "{{ secrets.pushbullet.apikey }}"
      title: "{{ series_name }} {{ series_id }}"
      body: "{{ title }}\n\nSize: {{ content_size }}MB"

# disini semua template diatas digunakan
tasks:

  tv-download:
    priority: 1
    template: [transmission-global, reject, tv, rss-tv]
    torrent_alive: 10
# filter pertama untuk file yang akan didownload berdasarkan dari size
# pastikan juga filter ini masuk range dari quality yang dicantumkan
# untuk tv show dengan filter quality "!720p+"
    content_size:
      max: 900
      min: 20

# prioritas download pertama
    transmission:
      queue_position: 0

  movies-download:
    priority: 2
    template: [transmission-global, reject, movies, rss-movies]
    torrent_alive: 10
# prioritas download pertama
    transmission:
      queue_position: 0
    content_size:
      max: 4000
      min: 20    

  anime-download:
    priority: 3
    template: [transmission-global, anime, rss-anime]
    torrent_alive: 10
# untuk anime 300mb+ sudah keterlaluan
    content_size:
      max: 400
      min: 20


# cari dan download episode sebelumnya yang tersedia dipiratebay, extratorrent
# atau limetorrent. Note jika jumlah series yang tercantum di list thetvdb atau
# di target folder series ada banyak, jangan kaget kalau jumlah torrent di transmission
# akan menumpuk banyak.
# tambahan note untuk folder series sudah ada seri dari download manual, pastikan nama folder
# sesuai dengan nama di thetvdb list, untuk mempermudah pencarian.

  download-series-jadul:
    priority: 4
    template: [transmission-global, reject]
    configure_series:
      from:
        filesystem: 
          path: '{{ secrets.folder.series }}'
      settings:
        identified_by: ep
    thetvdb_lookup: yes
    torrent_alive: 1
    disable:
      - seen
      - seen_info_hash
    discover:
      release_estimations: ignore
      interval: 15 minutes
      what:
        - next_series_episodes:
            from_start: yes
      from:
        - piratebay:
            category: highres tv
        - extratorrent:
            category: tv
        - limetorrents:
            category: tv
# set semua torrent dari list ini ada diposisi bawah jadi tidak mendahului
# series terbaru, sesuaikan juga dengan 'download-queue-size' di settings.json
# transmission-daemon
    transmission:
      queue_position: 10
      path: '/home/{{ secrets.user }}/torrent/Series/{{tvdb_series_name}}'
    set:
      label: tv
    content_size:
      max: 500
      min: 20
    pushbullet:
      apikey: "{{ secrets.pushbullet.apikey }}"
      title: "{{ series_name }} {{ series_id }}"
      body: "{{ title }}\n\nSize: {{ content_size }}MB"

  download-anime-jadul:
    priority: 4
    template: [transmission-global]
    configure_series:
      from:
        filesystem: 
          path: '{{ secrets.folder.anime }}'
      settings:
        identified_by: sequence
    thetvdb_lookup: yes
    torrent_alive: 1
    disable:
      - seen
      - seen_info_hash
    discover:
      release_estimations: ignore
      interval: 15 minutes
      what:
        - next_series_episodes:
            from_start: yes
      from:
        - extratorrent:
            category: anime
        - limetorrents:
            category: anime
    transmission:
      queue_position: 10
      path: '/home/{{ secrets.user }}/torrent/anime/{{series_name}}'
    set:
      label: anime
    content_size:
      max: 500
      min: 20
    pushbullet:
      apikey: "{{ secrets.pushbullet.apikey }}"
      title: "{{ series_name }} {{ series_id }}"
      body: "{{ title }}\n\nSize: {{ content_size }}MB"

# task ini berguna untuk memasukkan daftar film dari list watchlist di
# trakt.tv kedalam list flexget (mymovies), yang akan dijadikan acuan 
# untuk download dari rss
  import-movie-list:
    trakt_list:
      username: '{{ secrets.trakt.user }}'
      account: '{{ secrets.trakt.account }}'
      list: watchlist
      type: movies
    accept_all: yes
    seen: local
    list_add:
      - movie_list: mymovies

# piratebay
  movies-search:
    trakt_lookup: yes
    priority: 5
    discover:
      what:
        - movie_list: mymovies
      from:
        - piratebay:
            category: movies
        - limetorrents:
            category: movies
        - extratorrent:
            category: movies
      interval: 6 hours # bisa menggunakan minutes, hours, atau days
    torrent_alive: 10
    quality: dvdrip+
    template: [transmission-global, reject]
    transmission:
      path: '{{ secrets.folder.movies }}'
      queue_position: 20
    set:
      label: movies
    pushbullet:
      apikey: "{{ secrets.pushbullet.apikey }}"
      title: "{{ imdb_name }}"
      body: "{{ title }}\n \nSize: {{ content_size }}MB"

# pindahkan file dari folder download ke exists
  move-series:
    priority: 7
    disable:
      - seen
      - seen_info_hash
      - retry_failed
    metainfo_series: yes
    thetvdb_lookup: yes
    filesystem:
      path: '/home/{{ secrets.user }}/torrent/Series/'
      recursive: yes
      retrieve: files
      regexp: '.*\.(avi|mkv|mp4)$'
    accept_all: yes
    move:
      to: "/{{ secrets.folder.series }}/{{tvdb_series_name}}/Season {{tvdb_season}}"
      along:
        extensions:
          - srt
          - sub
        subdirs:
          - subs
    exec:
      on_exit:
        phase: find /home/{{ secrets.user }}/torrent/Series/* -type d -empty -delete

# pindahkan file dari folder download ke exists
  move-movies:
    priority: 8
    disable:
      - seen
      - seen_info_hash
      - retry_failed
    metainfo_series: yes
    imdb_lookup: yes
    filesystem:
      path: '/home/{{ secrets.user }}/torrent/Movies/'
      recursive: yes
      retrieve: files
      regexp: '.*\.(avi|mkv|mp4)$'
    accept_all: yes
    move:
      to: "/{{ secrets.folder.movies}}/{{ imdb_name }}"
      along:
        extensions:
          - srt
          - sub
        subdirs:
          - subs
    exec:
      on_exit:
        phase: find /home/{{ secrets.user }}/torrent/Movies/* -type d -empty -delete

# pindahkan file dari folder download ke exists
  move-anime:
    priority: 9
    disable:
      - seen
      - seen_info_hash
      - retry_failed
    parsing:
      series: guessit
    filesystem:
      path: '/home/{{ secrets.user }}/torrent/anime/'
      recursive: yes
      retrieve: files
      regexp: '.*\.(avi|mkv|mp4)$'
    accept_all: yes
    metainfo_series: yes
    move:
      to: "/{{ secrets.folder.anime }}/{{series_name}}/"
    exec:
      allow_background: yes
      on_exit:
        phase: find /home/{{ secrets.user }}/torrent/anime/* -type d -empty -delete


# hapus list transmission yang sudah selesai didownload lebih dari 1 jam
  clean-up:
    clean_transmission:
      host: localhost
      port: 9091
      username: transmission
      password: transmission
      finished_for: 1 hours
    disable: details

##### isi database dengan file yang sudah ada di library

  populate-series-db:
    priority: 1
    metainfo_series: yes
    thetvdb_lookup: yes
    seen: local
    filesystem:
      path: '/{{ secrets.folder.series }}'
      recursive: yes
      retrieve: files
      regexp: '.*\.(avi|mkv|mp4)$'
    accept_all: yes
    configure_series:
      from:
        filesystem:
          path: '/{{secrets.folder.series}}'
          retrieve: dirs
      settings:
        tracking: no

# bisa juga dicantumkan dalam task, seperti di task movies-search
schedules:

  - tasks: [move-series, move-movies, move-anime, populate-series-db, clean-up]
    interval:
      hours: 1

  - tasks: [reject, tv-download, anime-download]
    interval:
      hours: 2

  - tasks: [import-movie-list, reject, movies-download]
    interval:
      hours: 3
