#
# Author: Christian Alexander <alexforsale@yahoo.com>
#
variables: secrets.yml

templates:

  global:
# semua task akan berhenti jika sisa space untuk path - path dibawah ini kurang
# dari 5000mb
    free_space:
      path: /home/{? user ?}/torrent/
      space: 5000
    pathscrub: windows
    no_entries_ok: yes

