#
# Author: Christian Alexander <alexforsale@yahoo.com>
#
variables: secrets.yml

templates:

  global:
# semua task akan berhenti jika sisa space untuk path - path dibawah ini kurang
# dari 5000mb
    free_space:
      path: '{? media.partition ?}'
      space: 5000
    pathscrub: windows
    no_entries_ok: yes

tasks:
  versioncheck:
    version_checker:
      check_for_dev_version: yes
      interval: 1

  check_existing_movies:
    filesystem:
      path:
        - '{? folder.movies ?}'
        - '{? staging.movies ?}'
      retrieve:
        - files
        - dirs
      recursive: yes
      regexp: '.*\.(avi|mkv|mp4|m4v|iso)$'
    only_new: yes
    imdb_lookup: yes
    trakt_lookup: yes
    nfo_lookup: yes
    parsing:
      movie: guessit
    list_add:
      - movie_list: existing movies

  check_existing_episodes:
    filesystem:
      path:
        - '{? folder.series ?}'
        - '{? staging.series ?}'
      retrieve:
        - files
        - dirs
      recursive: yes
      regexp: '.*\.(avi|mkv|mp4|m4v|iso)$'
    all_series: yes
    only_new: yes
    metainfo_series: yes
    thetvdb_lookup: yes
    parsing:
      series: guessit
    list_add:
      - entry_list: existing episodes
    set_series_begin: yes

  update_series_list:
    disable:
      - seen
    filesystem:
      path:
        - '{? folder.series ?}'
        - '{? staging.series ?}'
      retrieve: dirs
      recursive: no
    metainfo_series: yes
    thetvdb_lookup: yes
    parsing:
      series: guessit
    manipulate:
      - title:
          replace:
            regexp: '$'
            format: ' S01E01'
    accept_all: yes
    list_add:
      - entry_list: existing series
